# Generated by Django 2.1.7 on 2019-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('no_of_students', models.CharField(max_length=5)),
                ('max_no_of_students', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=3)),
                ('course_description', models.TextField(max_length=800)),
                ('trainer', models.CharField(max_length=50)),
            ],
        ),
    ]
