# Generated by Django 2.1.7 on 2019-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('session_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=2)),
            ],
        ),
    ]
