# Generated by Django 2.1.7 on 2019-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_classroomsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsession',
            name='course_id',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroomsession',
            name='session_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
