# Generated by Django 2.1.7 on 2019-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20190326_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsession',
            name='course_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
