# Generated by Django 2.1.7 on 2019-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentcourse_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='course_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
